# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'podinstall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for podinstall
pod 'Alamofire'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'ObjectMapper', '~> 3.5'
end
